#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
TMP="$(mktemp -d /tmp/encore-guest-extension.XXXXXX)"
trap 'rm -rf -- "$TMP"' EXIT

gcc -m32 -c -nostdlib -fno-pic -fno-pie \
  -o "$TMP/extension.o" "$ROOT/guest-extensions/extension.S"
ld -m elf_i386 -T "$ROOT/guest-extensions/linker.ld" \
  -o "$TMP/extension.elf" "$TMP/extension.o"
objcopy -O binary --gap-fill 0 "$TMP/extension.elf" "$TMP/extension.bin"

python3 - "$TMP/extension.bin" "$TMP/payload.inc" <<'PY'
from pathlib import Path
import sys
data = Path(sys.argv[1]).read_bytes()
if len(data) > 0x10000:
    raise SystemExit(f"guest extension is {len(data)} bytes; 64 KiB reserve exceeded")
lines = ["/* Generated by guest-extensions/build.sh; do not edit. */",
         f"#define P2K_GE_PAYLOAD_SIZE {len(data)}u",
         "static const uint8_t p2k_ge_payload[P2K_GE_PAYLOAD_SIZE] = {"]
for off in range(0, len(data), 12):
    lines.append("    " + ", ".join(f"0x{x:02x}" for x in data[off:off+12]) + ",")
lines.append("};")
Path(sys.argv[2]).write_text("\n".join(lines) + "\n")
PY

DEST="$ROOT/qemu/p2k-guest-extension-payload.inc"
if [[ "${1:-}" == --check ]]; then
  cmp -s "$TMP/payload.inc" "$DEST" || {
    echo "guest extension payload is stale; run guest-extensions/build.sh" >&2
    exit 1
  }
  exit 0
fi
if [[ ! -f "$DEST" ]] || ! cmp -s "$TMP/payload.inc" "$DEST"; then
  install -m 0644 "$TMP/payload.inc" "$DEST"
fi
echo "[guest-extensions] payload: $(stat -c %s "$TMP/extension.bin") bytes"
