/*
 * ============================================================================
 * STATUS: TEMPORARY SYMPTOM PATCH — replace with proper QEMU device behavior.
 *
 * Why temporary: this module pins IDT[0x20] to a hand-injected stub at
 * physical 0x500 and re-arms it indefinitely on a virtual-clock timer.
 * That fights the guest's own IDT writes and embeds an emulator-side
 * timing assumption (IRQ0 must always EOI+IRET cleanly) into RAM.
 *
 * Removal condition: stop pinning the IDT entry once
 *   (a) the QEMU i8259 + i8254 path is wired so that IRQ0 deliveries
 *       are gated by the *real* CPU IF flag and IDT contents (no force
 *       inject), AND
 *   (b) the guest's own clkint installer (set_evec(0x20, clkint) inside
 *       XINU's clkinit) is reached naturally — verified by IDT[0x20]
 *       holding a >0x100000 address at the point the first PIT tick
 *       arrives — at which point this whole file can be deleted.
 *
 * Until then: keep the env-var kill switch P2K_NO_IRQ0_SHIM so the
 * patch can be disabled when working on the real fix.
 * ============================================================================
 *
 * pinball2000 IRQ0 early-shim.
 *
 * Problem: in our QEMU build of swe1, IDT[0x20] is initialised by XINU's
 * sysinit() to an autogenerated trap-dispatcher stub at game-code address
 * ~0x232004 (push 0x20; jmp 0x231e75 → Xinu trap! exception 32 → "Trap to
 * monitor" halt).  Real clkint is only installed later by clkinit().  The
 * unicorn.old gate `IDT[0x20] > 0x100000` distinguishes XINU's *generic
 * EOI+IRET stub* (at 0x20000000 in their layout) from the real handler;
 * but our autogen stub is itself in game code (>0x100000) AND it panics.
 * So if PIC fix-up unmasks IRQ0 before XINU installs real clkint, the
 * very first PIT edge tips the system into the trap monitor.
 *
 * Fix: inject a 5-byte "ack-EOI-and-IRET" stub at low RAM 0x500 and
 * point IDT[0x20] at it.  This is a one-shot, fired as soon as the PIC
 * has been ICW-initialised AND XINU has loaded an IDT (idt.base != 0).
 * When XINU later calls set_evec(0x20, clkint) during clkinit(), it
 * overwrites our IDT entry — our stub becomes inert with no further
 * handover needed.
 *
 * Why 0x500?  unicorn.old/src/cpu.c:589 uses 0x500 for its Cyrix 0F3C
 * emulator and IDT[6] redirect; that area is XINU "low memory below the
 * BIOS data area / IVT" — never overwritten by the running game.
 *
 * The stub:
 *     B0 20         mov al, 0x20    ; non-specific EOI
 *     E6 20         out 0x20, al    ; ack to master 8259
 *     CF            iret
 */

#include "qemu/osdep.h"
#include "qemu/error-report.h"
#include "qemu/timer.h"
#include "hw/intc/i8259.h"
#include "hw/isa/i8259_internal.h"
#include "exec/cpu-common.h"
#include "target/i386/cpu.h"

#include "p2k-internal.h"

#define P2K_IRQ0_SHIM_ADDR  0x00000500u
#define P2K_IRQ0_SHIM_POLL  (200 * 1000)          /* 0.2 ms — re-poll fast */

static const uint8_t p2k_irq0_shim_code[5] = {
    0xB0, 0x20,           /* mov al, 0x20      */
    0xE6, 0x20,           /* out 0x20, al      */
    0xCF,                 /* iret              */
};

static QEMUTimer *p2k_irq0_shim_timer;
static bool       p2k_irq0_shim_installed;

static bool p2k_pic_ready(void)
{
    return isa_pic && isa_pic->irq_base != 0;
}

static bool p2k_idt_loaded(CPUX86State **out_env)
{
    CPUState *cs;
    CPU_FOREACH(cs) {
        X86CPU *cpu = X86_CPU(cs);
        CPUX86State *env = &cpu->env;
        if (env->idt.base != 0 && env->idt.limit >= 0x20 * 8 + 7) {
            *out_env = env;
            return true;
        }
    }
    return false;
}

/* Heuristic: is the IDT[0x20] target the XINU autogen panic dispatcher?
 * That stub starts with the unmistakable signature
 *   55 89 E5 60 6A 20 E9 ?? ?? ?? ??
 *   (push ebp; mov ebp,esp; pusha; push 0x20; jmp <ko>)
 * Any other target — including a future real clkint installed by
 * XINU's clkinit() — is left alone, so the shim self-retires when the
 * guest is finally ready. */
static bool p2k_idt20_is_panic_stub(uint32_t off)
{
    static const uint8_t sig[7] = {
        0x55, 0x89, 0xE5, 0x60, 0x6A, 0x20, 0xE9
    };
    if (off < 0x100000 || off > 0x00f00000) {
        return false;
    }
    uint8_t buf[7];
    cpu_physical_memory_read(off, buf, sizeof(buf));
    return memcmp(buf, sig, sizeof(sig)) == 0;
}

static bool p2k_shim_active = true;   /* flipped to false on self-retire */

static void p2k_irq0_shim_disarm(void)
{
    if (p2k_irq0_shim_timer) {
        timer_free(p2k_irq0_shim_timer);
        p2k_irq0_shim_timer = NULL;
    }
}

static void p2k_irq0_shim_tick(void *opaque)
{
    CPUX86State *env = NULL;
    if (p2k_shim_active && p2k_pic_ready() && p2k_idt_loaded(&env)) {
        uint32_t idt_off = env->idt.base + 0x20 * 8;
        uint8_t  gate[8];
        cpu_physical_memory_read(idt_off, gate, sizeof(gate));
        uint32_t cur_off = gate[0] | (gate[1] << 8) |
                           (gate[6] << 16) | (gate[7] << 24);

        bool is_shim = (cur_off == P2K_IRQ0_SHIM_ADDR);
        bool is_panic = !is_shim && p2k_idt20_is_panic_stub(cur_off);

        if (is_panic) {
            cpu_physical_memory_write(P2K_IRQ0_SHIM_ADDR,
                                      p2k_irq0_shim_code,
                                      sizeof(p2k_irq0_shim_code));
            gate[0] = (uint8_t)(P2K_IRQ0_SHIM_ADDR & 0xff);
            gate[1] = (uint8_t)((P2K_IRQ0_SHIM_ADDR >> 8) & 0xff);
            gate[6] = (uint8_t)((P2K_IRQ0_SHIM_ADDR >> 16) & 0xff);
            gate[7] = (uint8_t)((P2K_IRQ0_SHIM_ADDR >> 24) & 0xff);
            cpu_physical_memory_write(idt_off, gate, sizeof(gate));
            if (!p2k_irq0_shim_installed) {
                info_report("pinball2000: IRQ0 EOI+IRET shim installed at "
                            "0x%x; IDT[0x20] redirected from panic stub "
                            "0x%08x", P2K_IRQ0_SHIM_ADDR, cur_off);
                p2k_irq0_shim_installed = true;
            }
        } else if (!is_shim) {
            /* Guest installed a real clkint (or any non-panic handler).
             * Step aside permanently — let the natural PIT path run.
             * Disarm the timer; we don't repair IDT[0x20] post-retirement
             * (no observed need; current code already gated all repair on
             * p2k_shim_active=true). */
            info_report("pinball2000: IRQ0 shim retiring — guest installed "
                        "a real handler at IDT[0x20]=0x%08x", cur_off);
            p2k_shim_active = false;
            p2k_irq0_shim_disarm();
            return;
        }
    }
    timer_mod(p2k_irq0_shim_timer,
              qemu_clock_get_ns(QEMU_CLOCK_VIRTUAL) + P2K_IRQ0_SHIM_POLL);
}

void p2k_install_irq0_shim(void)
{
    const char *off = getenv("P2K_NO_IRQ0_SHIM");
    if (off && *off && off[0] != '0') {
        info_report("pinball2000: IRQ0 shim disabled by P2K_NO_IRQ0_SHIM");
        return;
    }
    p2k_irq0_shim_timer = timer_new_ns(QEMU_CLOCK_VIRTUAL,
                                       p2k_irq0_shim_tick, NULL);
    timer_mod(p2k_irq0_shim_timer,
              qemu_clock_get_ns(QEMU_CLOCK_VIRTUAL) + P2K_IRQ0_SHIM_POLL);
    info_report("pinball2000: IRQ0 shim installer armed (poll %d ms)",
                (int)(P2K_IRQ0_SHIM_POLL / 1000000));
}
