/*
 * pinball2000 IRQ0 early-shim.
 *
 * Problem: in our QEMU build of swe1, IDT[0x20] is initialised by XINU's
 * sysinit() to an autogenerated trap-dispatcher stub at game-code address
 * ~0x232004 (push 0x20; jmp 0x231e75 → Xinu trap! exception 32 → "Trap to
 * monitor" halt).  Real clkint is only installed later by clkinit().  The
 * unicorn.old gate `IDT[0x20] > 0x100000` distinguishes XINU's *generic
 * EOI+IRET stub* (at 0x20000000 in their layout) from the real handler;
 * but our autogen stub is itself in game code (>0x100000) AND it panics.
 * So if PIC fix-up unmasks IRQ0 before XINU installs real clkint, the
 * very first PIT edge tips the system into the trap monitor.
 *
 * Fix: inject a 5-byte "ack-EOI-and-IRET" stub at low RAM 0x500 and
 * point IDT[0x20] at it.  This is a one-shot, fired as soon as the PIC
 * has been ICW-initialised AND XINU has loaded an IDT (idt.base != 0).
 * When XINU later calls set_evec(0x20, clkint) during clkinit(), it
 * overwrites our IDT entry — our stub becomes inert with no further
 * handover needed.
 *
 * Why 0x500?  unicorn.old/src/cpu.c:589 uses 0x500 for its Cyrix 0F3C
 * emulator and IDT[6] redirect; that area is XINU "low memory below the
 * BIOS data area / IVT" — never overwritten by the running game.
 *
 * The stub:
 *     B0 20         mov al, 0x20    ; non-specific EOI
 *     E6 20         out 0x20, al    ; ack to master 8259
 *     CF            iret
 */

#include "qemu/osdep.h"
#include "qemu/error-report.h"
#include "qemu/timer.h"
#include "hw/intc/i8259.h"
#include "hw/isa/i8259_internal.h"
#include "exec/cpu-common.h"
#include "target/i386/cpu.h"

#include "p2k-internal.h"

#define P2K_IRQ0_SHIM_ADDR  0x00000500u
#define P2K_IRQ0_SHIM_POLL  (1 * 1000 * 1000)     /* 1 ms */

static const uint8_t p2k_irq0_shim_code[5] = {
    0xB0, 0x20,           /* mov al, 0x20      */
    0xE6, 0x20,           /* out 0x20, al      */
    0xCF,                 /* iret              */
};

static QEMUTimer *p2k_irq0_shim_timer;
static bool       p2k_irq0_shim_installed;

static bool p2k_pic_ready(void)
{
    return isa_pic && isa_pic->irq_base != 0;
}

static bool p2k_idt_loaded(CPUX86State **out_env)
{
    CPUState *cs;
    CPU_FOREACH(cs) {
        X86CPU *cpu = X86_CPU(cs);
        CPUX86State *env = &cpu->env;
        if (env->idt.base != 0 && env->idt.limit >= 0x20 * 8 + 7) {
            *out_env = env;
            return true;
        }
    }
    return false;
}

static void p2k_irq0_shim_tick(void *opaque)
{
    CPUX86State *env = NULL;
    if (!p2k_irq0_shim_installed && p2k_pic_ready() && p2k_idt_loaded(&env)) {
        /* Write the EOI+IRET stub to low RAM. */
        cpu_physical_memory_write(P2K_IRQ0_SHIM_ADDR,
                                  p2k_irq0_shim_code,
                                  sizeof(p2k_irq0_shim_code));

        /* Patch IDT[0x20]:
         *   bytes 0..1 = offset_lo
         *   bytes 2..3 = selector
         *   byte  4    = zero
         *   byte  5    = type/attr
         *   bytes 6..7 = offset_hi
         * Read the current entry, replace only the offset, keep selector
         * and attributes that XINU set up. */
        uint32_t idt_off = env->idt.base + 0x20 * 8;
        uint8_t  gate[8];
        cpu_physical_memory_read(idt_off, gate, sizeof(gate));

        gate[0] = (uint8_t)(P2K_IRQ0_SHIM_ADDR & 0xff);
        gate[1] = (uint8_t)((P2K_IRQ0_SHIM_ADDR >> 8) & 0xff);
        gate[6] = (uint8_t)((P2K_IRQ0_SHIM_ADDR >> 16) & 0xff);
        gate[7] = (uint8_t)((P2K_IRQ0_SHIM_ADDR >> 24) & 0xff);

        cpu_physical_memory_write(idt_off, gate, sizeof(gate));
        p2k_irq0_shim_installed = true;
        info_report("pinball2000: IRQ0 EOI+IRET shim installed at 0x%x; "
                    "IDT[0x20] redirected (will be overridden by clkint)",
                    P2K_IRQ0_SHIM_ADDR);
        /* One-shot: do not re-arm. */
        return;
    }
    timer_mod(p2k_irq0_shim_timer,
              qemu_clock_get_ns(QEMU_CLOCK_VIRTUAL) + P2K_IRQ0_SHIM_POLL);
}

void p2k_install_irq0_shim(void)
{
    p2k_irq0_shim_timer = timer_new_ns(QEMU_CLOCK_VIRTUAL,
                                       p2k_irq0_shim_tick, NULL);
    timer_mod(p2k_irq0_shim_timer,
              qemu_clock_get_ns(QEMU_CLOCK_VIRTUAL) + P2K_IRQ0_SHIM_POLL);
    info_report("pinball2000: IRQ0 shim installer armed (poll %d ms)",
                (int)(P2K_IRQ0_SHIM_POLL / 1000000));
}
